import './style.css';
import { ClearLogs, CloseFirewallPort, FirewallStatus, GetState, ListPrinters, OpenFirewallPort, SaveSettings, SendTestData, StartServer, StopServer, TestConnection, Version } from '../wailsjs/go/main/App';
import { BrowserOpenURL } from '../wailsjs/runtime/runtime';

const languages={ru:'Русский',en:'English',de:'Deutsch',zh_CN:'简体中文',es:'Español'};
const dictionaries={
ru:{server:'Сервер',settings:'Настройки',serverLead:'Управление сетевым сервером печати и выбранным локальным принтером.',configuration:'Конфигурация',printer:'Принтер',selectPrinter:'Выберите принтер',noPrinters:'Принтеры не найдены',refresh:'Обновить список',port:'Порт',address:'Адрес',save:'Сохранить конфигурацию',status:'Статус сервера',running:'Работает',stopped:'Остановлен',ready:'Сервер готов к запуску',listening:'Прослушивается порт',endpoint:'Адрес подключения',controls:'Управление',start:'Запустить сервер',stop:'Остановить сервер',autoStart:'Автозапуск',autoStartHint:'Запускать вместе с приложением',log:'Журнал сервера',clear:'Очистить',readyLog:'Приложение готово к работе',limitsHint:'Лимиты можно изменить в настройках',settingsLead:'Параметры приложения и ограничения сервера.',application:'Приложение',language:'Язык интерфейса',languageHint:'Изменения применяются сразу.',minimize:'Сворачивать в системный трей',minimizeHint:'Оставлять приложение работающим в фоне.',network:'Сеть и лимиты',jobSize:'Задание, МБ',connections:'Подключения',queue:'Очередь',timeout:'Таймаут, сек.',lan:'Разрешить печать из локальной сети',lanHint:'Для LAN требуется общий токен длиной не менее 24 символов.',token:'Общий токен',apply:'Применить настройки',about:'О программе',version:'Версия',originalAuthor:'Автор оригинального проекта',goContributor:'Go-версия',saved:'Настройки сохранены',started:'Сервер запущен',stoppedLog:'Сервер остановлен'},
en:{server:'Server',settings:'Settings',serverLead:'Manage the network print server and selected local printer.',configuration:'Configuration',printer:'Printer',selectPrinter:'Select a printer',noPrinters:'No printers found',refresh:'Refresh list',port:'Port',address:'Address',save:'Save configuration',status:'Server status',running:'Running',stopped:'Stopped',ready:'Server is ready to start',listening:'Listening on port',endpoint:'Endpoint',controls:'Controls',start:'Start server',stop:'Stop server',autoStart:'Auto-start',autoStartHint:'Start with the application',log:'Server log',clear:'Clear',readyLog:'Application is ready',limitsHint:'Limits can be changed in Settings',settingsLead:'Application preferences and server limits.',application:'Application',language:'Interface language',languageHint:'Changes apply immediately.',minimize:'Minimize to system tray',minimizeHint:'Keep the application running in the background.',network:'Network and limits',jobSize:'Job, MB',connections:'Connections',queue:'Queue',timeout:'Timeout, sec.',lan:'Allow local network printing',lanHint:'LAN requires a shared token at least 24 characters long.',token:'Shared token',apply:'Apply settings',about:'About',version:'Version',originalAuthor:'Original project author',goContributor:'Go version',saved:'Settings saved',started:'Server started',stoppedLog:'Server stopped'}
};
// The original app offered five UI languages. English is the complete fallback;
// these dictionaries keep the primary navigation and restored settings native.
dictionaries.de={...dictionaries.en,server:'Server',settings:'Einstellungen',serverLead:'Netzwerk-Druckserver und lokalen Drucker verwalten.',configuration:'Konfiguration',printer:'Drucker',selectPrinter:'Drucker auswählen',noPrinters:'Keine Drucker gefunden',refresh:'Liste aktualisieren',port:'Port',address:'Adresse',save:'Konfiguration speichern',status:'Serverstatus',running:'Läuft',stopped:'Angehalten',ready:'Server ist startbereit',controls:'Steuerung',start:'Server starten',stop:'Server stoppen',autoStart:'Autostart',log:'Serverprotokoll',clear:'Leeren',settingsLead:'Anwendungseinstellungen und Serverlimits.',application:'Anwendung',language:'Sprache',minimize:'In den Infobereich minimieren',network:'Netzwerk und Limits',jobSize:'Auftrag, MB',connections:'Verbindungen',queue:'Warteschlange',timeout:'Zeitlimit, Sek.',lan:'Drucken im lokalen Netzwerk erlauben',token:'Gemeinsames Token',apply:'Einstellungen anwenden',about:'Info',originalAuthor:'Autor des Originalprojekts',saved:'Einstellungen gespeichert'};
dictionaries.es={...dictionaries.en,server:'Servidor',settings:'Ajustes',serverLead:'Administre el servidor de impresión y la impresora local.',configuration:'Configuración',printer:'Impresora',selectPrinter:'Seleccionar impresora',noPrinters:'No se encontraron impresoras',refresh:'Actualizar lista',port:'Puerto',address:'Dirección',save:'Guardar configuración',status:'Estado del servidor',running:'Activo',stopped:'Detenido',ready:'El servidor está listo',controls:'Controles',start:'Iniciar servidor',stop:'Detener servidor',autoStart:'Inicio automático',log:'Registro del servidor',clear:'Limpiar',settingsLead:'Preferencias de la aplicación y límites del servidor.',application:'Aplicación',language:'Idioma de la interfaz',minimize:'Minimizar a la bandeja',network:'Red y límites',jobSize:'Trabajo, MB',connections:'Conexiones',queue:'Cola',timeout:'Tiempo de espera, seg.',lan:'Permitir impresión en red local',token:'Token compartido',apply:'Aplicar ajustes',about:'Acerca de',originalAuthor:'Autor del proyecto original',saved:'Ajustes guardados'};
dictionaries.zh_CN={...dictionaries.en,server:'服务器',settings:'设置',serverLead:'管理网络打印服务器和所选的本地打印机。',configuration:'配置',printer:'打印机',selectPrinter:'选择打印机',noPrinters:'未找到打印机',refresh:'刷新列表',port:'端口',address:'地址',save:'保存配置',status:'服务器状态',running:'运行中',stopped:'已停止',ready:'服务器已准备好启动',controls:'控制',start:'启动服务器',stop:'停止服务器',autoStart:'自动启动',log:'服务器日志',clear:'清除',settingsLead:'应用程序首选项和服务器限制。',application:'应用程序',language:'界面语言',minimize:'最小化到系统托盘',network:'网络和限制',jobSize:'任务，MB',connections:'连接数',queue:'队列',timeout:'超时，秒',lan:'允许局域网打印',token:'共享令牌',apply:'应用设置',about:'关于',originalAuthor:'原项目作者',saved:'设置已保存'};
Object.assign(dictionaries.ru,{test:'Проверка',testLead:'Проверка доступности сервера и отправка тестовых данных.',connection:'Подключение',host:'Сервер',testConnection:'Проверить подключение',sendTest:'Отправить тестовые данные',testLog:'Журнал проверки',firewall:'Windows Firewall',firewallHint:'Входящее TCP-правило для частных сетей.',firewallOpen:'Порт открыт',firewallClosed:'Порт закрыт',openPort:'Открыть порт',closePort:'Закрыть порт',checking:'Проверка…',connected:'Подключение установлено',sent:'Тестовые данные отправлены'});
Object.assign(dictionaries.en,{test:'Test Client',testLead:'Check server availability and send test data.',connection:'Connection',host:'Server',testConnection:'Test connection',sendTest:'Send test data',testLog:'Test log',firewall:'Windows Firewall',firewallHint:'Inbound TCP rule for private networks.',firewallOpen:'Port is open',firewallClosed:'Port is closed',openPort:'Open port',closePort:'Close port',checking:'Checking…',connected:'Connection established',sent:'Test data sent'});
Object.assign(dictionaries.de,{test:'Testclient',testLead:'Serververfügbarkeit prüfen und Testdaten senden.',connection:'Verbindung',host:'Server',testConnection:'Verbindung testen',sendTest:'Testdaten senden',testLog:'Testprotokoll',firewall:'Windows-Firewall',firewallHint:'Eingehende TCP-Regel für private Netzwerke.',firewallOpen:'Port ist offen',firewallClosed:'Port ist geschlossen',openPort:'Port öffnen',closePort:'Port schließen',checking:'Prüfung…'});
Object.assign(dictionaries.es,{test:'Cliente de prueba',testLead:'Compruebe el servidor y envíe datos de prueba.',connection:'Conexión',host:'Servidor',testConnection:'Probar conexión',sendTest:'Enviar datos de prueba',testLog:'Registro de prueba',firewall:'Firewall de Windows',firewallHint:'Regla TCP entrante para redes privadas.',firewallOpen:'Puerto abierto',firewallClosed:'Puerto cerrado',openPort:'Abrir puerto',closePort:'Cerrar puerto',checking:'Comprobando…'});
Object.assign(dictionaries.zh_CN,{test:'测试客户端',testLead:'检查服务器可用性并发送测试数据。',connection:'连接',host:'服务器',testConnection:'测试连接',sendTest:'发送测试数据',testLog:'测试日志',firewall:'Windows 防火墙',firewallHint:'专用网络的入站 TCP 规则。',firewallOpen:'端口已打开',firewallClosed:'端口已关闭',openPort:'打开端口',closePort:'关闭端口',checking:'正在检查…'});
Object.assign(dictionaries.ru,{lanHint:'Сервер будет принимать задания от других компьютеров без токена.',firewallUnknown:'Состояние не проверено',checkFirewall:'Проверить'});
Object.assign(dictionaries.en,{lanHint:'The server will accept jobs from other computers without a token.',firewallUnknown:'Status not checked',checkFirewall:'Check'});
Object.assign(dictionaries.de,{lanHint:'Der Server nimmt Aufträge von anderen Computern ohne Token an.',firewallUnknown:'Status nicht geprüft',checkFirewall:'Prüfen'});
Object.assign(dictionaries.es,{lanHint:'El servidor aceptará trabajos de otros equipos sin token.',firewallUnknown:'Estado no comprobado',checkFirewall:'Comprobar'});
Object.assign(dictionaries.zh_CN,{lanHint:'服务器无需令牌即可接收其他计算机的任务。',firewallUnknown:'状态未检查',checkFirewall:'检查'});
Object.assign(dictionaries.ru,{systemStartup:'Автозапуск при старте системы',systemStartupHint:'Запускать PrinterOne после входа в Windows.'});
Object.assign(dictionaries.en,{systemStartup:'Start with Windows',systemStartupHint:'Launch PrinterOne after signing in to Windows.'});
Object.assign(dictionaries.de,{systemStartup:'Mit Windows starten',systemStartupHint:'PrinterOne nach der Windows-Anmeldung starten.'});
Object.assign(dictionaries.es,{systemStartup:'Iniciar con Windows',systemStartupHint:'Iniciar PrinterOne al entrar en Windows.'});
Object.assign(dictionaries.zh_CN,{systemStartup:'随 Windows 启动',systemStartupHint:'登录 Windows 后启动 PrinterOne。'});
let state,printers=[],page='server',appVersion='1.0.2',logs=[],testLogs=[],firewallOpen=false,firewallKnown=false,firewallPort=0;
const tr=k=>(dictionaries[state?.config?.language]||dictionaries.en)[k]||dictionaries.en[k]||k;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=n=>({server:'<svg viewBox="0 0 24 24"><path d="M5 5h14v5H5zM5 14h14v5H5zM8 7.5h.01M8 16.5h.01"/></svg>',settings:'<svg viewBox="0 0 24 24"><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7z"/><path d="M19 13.5v-3l-2-.7-.6-1.4.9-1.9-2.1-2.1-1.9.9-1.4-.6-.7-2h-3l-.7 2-1.4.6-1.9-.9-2.1 2.1.9 1.9-.6 1.4-2 .7v3l2 .7.6 1.4-.9 1.9 2.1 2.1 1.9-.9 1.4.6.7 2h3l.7-2 1.4-.6 1.9.9 2.1-2.1-.9-1.9.6-1.4z"/></svg>',printer:'<svg viewBox="0 0 24 24"><path d="M7 9V4h10v5M7 17H4v-7h16v7h-3M7 14h10v6H7z"/></svg>',refresh:'<svg viewBox="0 0 24 24"><path d="M20 7v5h-5M4 17v-5h5M18 11a7 7 0 0 0-12-3L4 12m2 1a7 7 0 0 0 12 3l2-4"/></svg>'}[n]||'');
const testIcon='<svg viewBox="0 0 24 24"><path d="m4 12 16-8-6 16-2-7z"/><path d="m12 13 8-9"/></svg>';

function shell(content){return `<aside class="sidebar"><div class="brand">${icon('printer')}<span>PrinterOne</span></div><nav><button class="nav-item ${page==='server'?'active':''}" data-page="server">${icon('server')}<span>${tr('server')}</span></button><button class="nav-item ${page==='test'?'active':''}" data-page="test">${testIcon}<span>${tr('test')}</span></button><button class="nav-item ${page==='settings'?'active':''}" data-page="settings">${icon('settings')}<span>${tr('settings')}</span></button></nav><div class="sidebar-foot">v1.0</div></aside><main class="page-${page}">${content}</main>`}
const header=(title,lead)=>`<header class="page-header"><div><h1>${title}</h1><p>${lead}</p></div></header>`;

function serverPage(){const c=state.config;const options=printers.length?`<option value="">${tr('selectPrinter')}</option>${printers.map(p=>`<option value="${esc(p)}" ${p===c.printer_name?'selected':''}>${esc(p)}</option>`).join('')}`:`<option value="">${tr('noPrinters')}</option>`;return shell(`${header(tr('server'),tr('serverLead'))}<section class="server-grid">
<article class="card config-card"><h2>${tr('configuration')}</h2><label><span>${tr('printer')}</span><div class="input-action"><select id="printer">${options}</select><button id="refresh-printers" class="icon-button" title="${tr('refresh')}">${icon('refresh')}</button></div></label><div class="field-row"><label><span>${tr('port')}</span><input id="port" type="number" min="1" max="65535" value="${c.port}"></label><label><span>${tr('address')}</span><input id="address" value="${esc(c.listen_address)}"></label></div><button id="save-server" class="primary">▣ &nbsp;${tr('save')}</button></article>
<article class="card status-card"><h2>${tr('status')}</h2><div class="status-line ${state.running?'is-running':''}"><i></i><strong>${state.running?tr('running'):tr('stopped')}</strong><em>${state.running?'Active':'Idle'}</em></div><p>${state.running?`${tr('listening')} ${c.port}`:tr('ready')}</p><hr><dl><div><dt>${tr('endpoint')}</dt><dd>${esc(state.running?(state.local_ip||c.listen_address):c.listen_address)}:${c.port}</dd></div><div><dt>${tr('printer')}</dt><dd>${esc(c.printer_name||'—')}</dd></div></dl></article>
<article class="card controls-card"><h2>${tr('controls')}</h2><button id="start" class="primary" ${state.running?'disabled':''}>▷ &nbsp;${tr('start')}</button><button id="stop" class="secondary" ${!state.running?'disabled':''}>■ &nbsp;${tr('stop')}</button><hr><div class="switch-row"><div><strong>${tr('autoStart')}</strong><small>${tr('autoStartHint')}</small></div><label class="switch"><input id="auto-start" type="checkbox" ${c.auto_start?'checked':''}><span></span></label></div></article></section>
<section class="card log-card"><div class="card-title"><h2>${tr('log')} <span class="live-dot">● Live</span></h2><button id="clear-log" class="small-button">⌫ ${tr('clear')}</button></div><div class="console">${serverLogHTML()}</div></section>`)}

function settingsPage(){const c=state.config,mb=Math.max(1,Math.round(c.max_job_bytes/1048576));return shell(`${header(tr('settings'),tr('settingsLead'))}<section class="settings-layout">
<article class="card"><h2>${tr('application')}</h2><div class="setting-row"><div><strong>${tr('language')}</strong><small>${tr('languageHint')}</small></div><select id="language">${Object.entries(languages).map(([code,name])=>`<option value="${code}" ${code===c.language?'selected':''}>${name}</option>`).join('')}</select></div><div class="setting-row"><div><strong>${tr('minimize')}</strong><small>${tr('minimizeHint')}</small></div><label class="switch"><input id="minimize" type="checkbox" ${c.minimize_to_tray?'checked':''}><span></span></label></div><div class="setting-row"><div><strong>${tr('systemStartup')}</strong><small>${tr('systemStartupHint')}</small></div><label class="switch"><input id="system-startup" type="checkbox" ${c.start_with_windows?'checked':''}><span></span></label></div></article>
<article class="card"><h2>${tr('network')}</h2><div class="limits-row"><label><span>${tr('jobSize')}</span><input id="max-mb" type="number" min="1" max="1024" value="${mb}"></label><label><span>${tr('connections')}</span><input id="connections" type="number" min="1" max="1000" value="${c.max_connections}"></label><label><span>${tr('queue')}</span><input id="queue" type="number" min="1" max="10000" value="${c.max_queued_jobs}"></label><label><span>${tr('timeout')}</span><input id="timeout" type="number" min="1" max="3600" value="${c.read_timeout_seconds}"></label></div><button id="save-settings" class="primary compact-save">▣ &nbsp;${tr('apply')}</button></article>
<article class="card firewall-card"><div><h2>${tr('firewall')}</h2><p>${tr('firewallHint')}</p></div><div class="firewall-actions"><span class="firewall-state ${firewallKnown&&firewallOpen?'open':''}">● ${firewallKnown?(firewallOpen?tr('firewallOpen'):tr('firewallClosed')):tr('firewallUnknown')} · TCP ${c.port}</span><button id="firewall-check" class="secondary">${tr('checkFirewall')}</button>${firewallKnown?`<button id="firewall-action" class="${firewallOpen?'secondary':'primary'}">${firewallOpen?tr('closePort'):tr('openPort')} ${c.port}</button>`:''}</div></article>
<article class="card about-card"><h2>${tr('about')}</h2><div class="about-grid"><div><strong>PrinterOne — Network Print Server</strong><p>${tr('version')}: ${esc(appVersion)}</p></div><div><span>${tr('originalAuthor')}</span><strong>Tieu M · xtieume@gmail.com</strong><a href="https://github.com/xtieume/PrinterOne">github.com/xtieume/PrinterOne</a></div><div><span>${tr('goContributor')}</span><strong>ashsoft ltd. · ashtray@me.com</strong><a href="https://github.com/ashtray01">github.com/ashtray01</a></div></div></article></section>`)}

function testPage(){const c=state.config;return shell(`${header(tr('test'),tr('testLead'))}<section class="test-layout"><article class="card test-connection"><h2>${tr('connection')}</h2><div class="test-fields"><label><span>${tr('host')}</span><input id="test-host" value="localhost"></label><label><span>${tr('port')}</span><input id="test-port" type="number" min="1" max="65535" value="${c.port}"></label><button id="test-connection" class="primary">⌁ &nbsp;${tr('testConnection')}</button></div></article><article class="card test-actions"><h2>${tr('controls')}</h2><button id="send-test" class="secondary">▷ &nbsp;${tr('sendTest')}</button></article><article class="card test-log-card"><div class="card-title"><h2>${tr('testLog')}</h2><button id="clear-test-log" class="small-button">⌫ ${tr('clear')}</button></div><div class="console">${(testLogs.length?testLogs:[`[INFO] ${tr('readyLog')}`]).map(esc).join('<br>')}</div></article></section>`)}

function render(){document.documentElement.lang=state.config.language==='zh_CN'?'zh-CN':state.config.language;document.querySelector('#app').innerHTML=page==='server'?serverPage():page==='test'?testPage():settingsPage();document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('a[href^="https://"]').forEach(a=>a.onclick=e=>{e.preventDefault();BrowserOpenURL(a.href)});page==='server'?bindServer():page==='test'?bindTest():bindSettings();if(page==='server')requestAnimationFrame(scrollServerLog)}
function serverLogHTML(){const lines=[...(state.logs||[]),...logs];return (lines.length?lines:[`[INFO] ${tr('readyLog')}`,`[INFO] ${tr('limitsHint')}`]).slice(-500).map(esc).join('<br>')}
function scrollServerLog(){const element=document.querySelector('.log-card .console');if(element)element.scrollTop=element.scrollHeight}
function pushLog(message){if(logs[logs.length-1]!==message)logs.push(message);if(logs.length>100)logs.splice(0,logs.length-100)}
function pushTestLog(message){if(testLogs[testLogs.length-1]!==message)testLogs.push(message);if(testLogs.length>200)testLogs.splice(0,testLogs.length-200)}
function configFromForm(){const v=id=>document.querySelector(id)?.value;return {...state.config,printer_name:v('#printer')??state.config.printer_name,port:v('#port')?Number(v('#port')):state.config.port,listen_address:v('#address')?.trim()||state.config.listen_address,auto_start:document.querySelector('#auto-start')?.checked??state.config.auto_start,language:v('#language')??state.config.language,minimize_to_tray:document.querySelector('#minimize')?.checked??state.config.minimize_to_tray,start_with_windows:document.querySelector('#system-startup')?.checked??state.config.start_with_windows,max_job_bytes:v('#max-mb')?Number(v('#max-mb'))*1048576:state.config.max_job_bytes,max_connections:v('#connections')?Number(v('#connections')):state.config.max_connections,max_queued_jobs:v('#queue')?Number(v('#queue')):state.config.max_queued_jobs,read_timeout_seconds:v('#timeout')?Number(v('#timeout')):state.config.read_timeout_seconds,lan_enabled:true,shared_token:''}}
async function save(next,message=tr('saved')){try{state=await SaveSettings(next);pushLog(`[OK] ${message}`);render();return true}catch(e){pushLog(`[ERROR] ${String(e)}`);render();return false}}
function bindServer(){document.querySelector('#refresh-printers').onclick=loadPrinters;document.querySelector('#save-server').onclick=()=>save(configFromForm());document.querySelector('#auto-start').onchange=()=>save(configFromForm());document.querySelector('#clear-log').onclick=async()=>{logs=[];await ClearLogs();state=await GetState();render()};document.querySelector('#start').onclick=async()=>{if(!await save(configFromForm()))return;try{state=await StartServer()}catch(e){pushLog(`[ERROR] ${String(e)}`)}render()};document.querySelector('#stop').onclick=async()=>{try{state=await StopServer()}catch(e){pushLog(`[ERROR] ${String(e)}`)}render()}}
function bindSettings(){document.querySelector('#language').onchange=e=>save({...state.config,language:e.target.value});document.querySelector('#minimize').onchange=e=>save({...state.config,minimize_to_tray:e.target.checked});document.querySelector('#system-startup').onchange=e=>save({...state.config,start_with_windows:e.target.checked});document.querySelector('#save-settings').onclick=()=>save(configFromForm());document.querySelector('#firewall-check').onclick=refreshFirewallStatus;const action=document.querySelector('#firewall-action');if(action)action.onclick=changeFirewall}
function bindTest(){const values=()=>[document.querySelector('#test-host').value.trim(),Number(document.querySelector('#test-port').value)];document.querySelector('#clear-test-log').onclick=()=>{testLogs=[];render()};document.querySelector('#test-connection').onclick=async()=>{const [host,port]=values();pushTestLog(`[INFO] ${tr('checking')} ${host}:${port}`);render();try{const address=await TestConnection(host,port);pushTestLog(`[OK] ${tr('connected')}: ${address}`)}catch(e){pushTestLog(`[ERROR] ${String(e)}`)}render()};document.querySelector('#send-test').onclick=async()=>{const [host,port]=values();try{const bytes=await SendTestData(host,port);pushTestLog(`[OK] ${tr('sent')}: ${bytes} bytes`)}catch(e){pushTestLog(`[ERROR] ${String(e)}`)}render()}}
async function refreshFirewallStatus(){firewallPort=state.config.port;const button=document.querySelector('#firewall-check');if(button){button.disabled=true;button.textContent=tr('checking')}try{firewallOpen=await FirewallStatus(firewallPort);firewallKnown=true}catch(e){firewallKnown=false;pushLog(`[ERROR] ${String(e)}`)}if(page==='settings')render()}
async function changeFirewall(){const port=state.config.port,button=document.querySelector('#firewall-action');button.disabled=true;button.textContent=tr('checking');try{if(firewallOpen)await CloseFirewallPort(port);else await OpenFirewallPort(port);firewallOpen=await FirewallStatus(port);firewallKnown=true}catch(e){pushLog(`[ERROR] ${String(e)}`)}render()}
async function loadPrinters(){document.querySelector('#refresh-printers')?.classList.add('spinning');try{printers=await ListPrinters()||[]}catch(e){pushLog(`[ERROR] ${String(e)}`)}render()}
async function init(){try{[state,appVersion]=await Promise.all([GetState(),Version()]);await loadPrinters()}catch(e){document.querySelector('#app').innerHTML=`<div class="fatal">PrinterOne<small>${esc(e)}</small></div>`}}init();
setInterval(async()=>{if(!state||page!=='server')return;try{state=await GetState();const consoleElement=document.querySelector('.log-card .console');if(consoleElement){consoleElement.innerHTML=serverLogHTML();scrollServerLog()}}catch{}},1000);
